# These are supported funding model platforms

github: no # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: no # Replace with a single Patreon username
open_collective: no # Replace with a single Open Collective username
ko_fi: no # Replace with a single Ko-fi username
tidelift: no # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: no # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: no # Replace with a single Liberapay username
issuehunt: no # Replace with a single IssueHunt username
lfx_crowdfunding: no # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: no # Replace with a single Polar username
buy_me_a_coffee: no # Replace with a single Buy Me a Coffee username
custom: no # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
